### ISSUE TITLE
[SUGGESTION] Overwrite Lidl color preferences to match the rest of the notifs

### ISSUE THREAD

**Issue by Janneske2001** [MrGcGamer/ColorMeNotifs-BugTracker#3]
## Is your feature request related to a problem? Please describe.

Kinda a compatibility problem with Liddell, as Liddell overwrites the color options of ColorMeNotifs  (which is frustrating for my OCD lmao)
## Describe the solution you'd like

Option to overwrite Liddell's color options, so the tiny Liddell banners match the color of the ColorMeNotifs banners.

## Describe alternatives you've considered

(otherwise a custom Liddell version with your dominant color algorithm instead of libKitten)
## Additional information

Already spoken about this on Litcord and Twitter

**Comment by MrGcGamer** [comment]
Done
